services:
  - type: static
    name: kanbananas-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://kanbananas-backend.onrender.com 