services:
  - type: web
    name: kanbananas-backend
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && node dist/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kanbananas_db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://kanbananas-frontend.onrender.com 